version: "3"
# Thanks to https://visibilityspots.org/dockerized-cloudflared-pi-hole.html
# echo "alias dns-up='cd /path/to/folder; docker-compose up -d'" >> ~/.bash_profile
services:
  doh-client:
    container_name: doh-client
    image: fardog/secureoperator:latest # google dns
    # image: visibilityspots/cloudflared:amd64 # cloudflare dns
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    dns:
      - 8.8.8.8
      - 8.8.4.4

  doh-server:
    container_name: doh-server
    image: satishweb/doh-server:v2.2.1
    environment:
      - UPSTREAM_DNS_SERVER=udp:10.0.0.3:53 
      - DOH_HTTP_PREFIX="/dns-query"
      - DOH_SERVER_LISTEN=":8053"
      - DOH_SERVER_TIMEOUT="10"
      - DOH_SERVER_TRIES="3"
      - DOH_SERVER_VERBOS="true"

  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:v5.0-amd64
    restart: unless-stopped
    ports:
      - "8111:80/tcp"
      #- "53:53/tcp"
      #- "53:53/udp"
    environment:
      - ServerIP=10.0.0.3
      - DNS1='10.0.0.2#53'
      - DNS2=''
      - IPv6=false
      - TZ=CEST-2
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=admin
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    
networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29