version: "3"
# Thanks to https://visibilityspots.org/dockerized-cloudflared-pi-hole.html
# echo "alias dns-up='cd /path/to/folder; docker-compose up -d'" >> ~/.bash_profile
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
        #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@38911.net"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      #- "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.4
  
  doh-client:
    container_name: doh-client
    image: fardog/secureoperator:latest # google dns
    # image: visibilityspots/cloudflared:amd64 # cloudflare dns
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    dns:
      - 8.8.8.8
      - 8.8.4.4

  doh-server:
    container_name: doh-server
    image: satishweb/doh-server:latest
    environment:
      UPSTREAM_DNS_SERVER: "udp:10.0.0.3:53"
      DOH_HTTP_PREFIX: "/dns-query"
      DOH_SERVER_LISTEN: ":8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOS: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.doh-server.rule=Host(`doh.zwobot.net`)"
      - "traefik.http.routers.doh-server.entrypoints=websecure"
      - "traefik.http.routers.doh-server.tls.certresolver=myresolver"
      - "traefik.http.services.doh-server.loadbalancer.server.port=8053"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.5
   
  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:v5.0-amd64
    restart: unless-stopped
    #ports::
      #- "8111:80/tcp"
      #- "53:53/tcp"
      #- "53:53/udp"
    environment:
      - ServerIP=10.0.0.3
      - DNS1='10.0.0.2#53'
      - DNS2=''
      - IPv6=false
      - TZ=CEST-2
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=admin
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pi-hole.rule=Host(`pihole.zwobot.net`)"
      - "traefik.http.routers.pi-hole.entrypoints=websecure"
      - "traefik.http.routers.pi-hole.tls.certresolver=myresolver"
      - "traefik.http.services.pi-hole.loadbalancer.server.port=80"
  
networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/28
